version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3-management  # Includes the management plugin
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"  # AMQP protocol port
      - "15672:15672"  # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # Persistent storage

volumes:
  rabbitmq_data: